apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-kube-permission
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-kube
subjects:
  - kind: ServiceAccount
    name: spark-kube
roleRef:
  kind: Role
  name: spark-kube-permission
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-kube
