apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: raw-to-parquet-12
  namespace: spark
spec:
  type: Scala
  mode: cluster
  sparkVersion: 3.1.1
  image: rg.fr-par.scw.cloud/benchmark-spark/raw-to-parquet:1
  imagePullPolicy: Always
  mainClass: devoxx.benchmark.RawToParquet
  mainApplicationFile: local:///opt/spark/examples/jars/raw-to-parquet-0.0.1-SNAPSHOT-shaded.jar
  driver:
    env:
      - name: REGION
        value: "fr-par"
      - name: INPUT
        value: "s3a://datalake-spark-benchmark/data/TPC-DS/10TB/customer_demographics"
      - name: OUTPUT
        value: "s3a://datalake-benchmark-spark/data/clean/TPC-DS/10TB/customer_demographics"
    envFrom:
      - secretRef:
          name: scw-secrets
    cores: 1
    memory: "1024m"
    hostNetwork: true
    labels:
      version: 3.1.1
    serviceAccount: spark-kube
  executor:
    serviceAccount: spark-kube
    env:
      - name: INPUT
        value: "s3a://datalake-spark-benchmark/data/TPC-DS/10TB/customer_demographics"
      - name: OUTPUT
        value: "s3a://datalake-benchmark-spark/data/clean/TPC-DS/10TB/customer_demographics"
    envFrom:
      - secretRef:
          name: scw-secrets
    cores: 2
    instances: 5
    memory: "8g"
