{{- $schema := .Values.sparkEventLogStorage.cloudProvider }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "spark-hs.fullname" . }}-spark-hs-config
data:
  spark-defaults.conf: |-
    {{- if .Values.sparkEventLogStorage.logDirectory }}
    spark.hadoop.fs.s3a.endpoint=https://s3.fr-par.scw.cloud
    {{- if eq $schema "azure" }}
    spark.hadoop.fs.azure.account.key.$storageAccount.blob.core.windows.net=$accessKey
    {{- end }}

    {{- end }}
