{{- $schema := .Values.sparkEventLogStorage.cloudProvider }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "spark-hs.fullname" . }}-spark-hs-config
data:
  spark-defaults.conf: |-
    spark.hadoop.fs.s3a.endpoint=s3.eu-west-1.amazonaws.com
    spark.history.fs.logDirectory={{ .Values.sparkEventLogStorage.logDirectory }}
    spark.hadoop.fs.s3a.aws.credentials.provider=com.amazonaws.auth.WebIdentityTokenCredentialsProvider
